services:

  gradio:
    build: 
      context: .
    pull_policy: build
    restart: unless-stopped
    # network_mode: host
    ports:
      # - "8080:7860"
      - "8080:8080"
    environment:
      - OPENAI_API_ENDPOINT_URL=${OPENAI_API_ENDPOINT_URL}
    volumes:
      - ./playground-data-review:/data:rw